-- Generated by hyprconf2lua v1.0.0
-- https://wiki.hypr.land/Configuring/
-- https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua
-- https://github.com/Prateek-squadron/hyprconf2lua
--
hl.monitor({
	output = "eDP-1",
	mode = "preferred",
	position = "0x0",
	scale = "auto",
})

-- work monitor
hl.monitor({
	output = "desc:Dell Inc. DELL U2721DE 9Y4T023",
	mode = "preferred",
	position = "auto-right",
	scale = 1.0,
})

-- work monitor
hl.monitor({
	output = "desc:Dell Inc. DELL U2719DC F8BYX13",
	mode = "preferred",
	position = "auto-right",
	scale = 1.0,
})

-- home monitor
hl.monitor({
	output = "desc:ViewSonic Corporation VP2458 VKR213640536",
	mode = "preferred",
	position = "auto-left",
	scale = 1,
})

--exec-once = waybar -c /home/fra/.config/waybar/waybar.conf -s /home/fra/.config/waybar/style.css
-- exec-once = ~/.config/waybar/launch_waybar.sh
--Stores only text data
--exec-once = ~/.config/hypr/scripts/lockscreentime.sh
--exec-once = /usr/lib/polkit-kde-authentication-agent-1 # authentication dialogue for GUI apps
--foot
-- Some default env vars.
--env = HYPRCURSOR_THEME,Adwaita

hl.env("HYPRCURSOR_THEME", "phinger-cursors-light")
hl.env("HYPRCURSOR_SIZE", 24)
hl.env("GSK_RENDERER", "gl")
--env = XCURSOR_SIZE,24

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.config({
	input = {
		kb_layout = "us",
		--kb_layout = us,dk
		kb_variant = "",
		kb_model = "",
		kb_options = "compose:caps",
		-- kb_options = grp:win_space_toggle, compose:caps
		kb_rules = "",
		follow_mouse = 1,
		touchpad = {
			natural_scroll = true,
			scroll_factor = 0.4,
		},
		sensitivity = 0,
		-- -1.0 - 1.0, 0 means no modification.
	},
})

hl.config({
	general = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		gaps_in = 3,
		gaps_out = 5,
		border_size = 2,
		-- TODO:
		col = {
			active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
			inactive_border = "rgba(595959aa)",
		},
		layout = "master",
		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
	},
})

hl.config({
	decoration = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		blur = {
			enabled = false,
			size = 3,
			passes = 1,
		},
		rounding = 10,
		shadow = {
			enabled = false,
		},
		--drop_shadow = yes
		--shadow_range = 4
		--shadow_render_power = 3
		--col.shadow = rgba(1a1a1aee)
	},
})

hl.config({
	animations = {
		enabled = true,
		-- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
	},
})

--master {

--    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

--    new_is_master = true

--}

-- gestures {

--     # See https://wiki.hyprland.org/Configuring/Variables/ for more

--     workspace_swipe = off

-- }

hl.config({
	misc = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		force_default_wallpaper = -1,
		-- Set to 0 to disable the anime mascot wallpapers
		key_press_enables_dpms = true,
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#executing for more

-- device:epic-mouse-v1 {

--    sensitivity = -0.5

--}

--

-- source = /home/fra/.config/hypr/workspace.conf -> requires manual conversion
require("workspace")

-- Example windowrule v1

-- windowrule = float, ^(kitty)$

-- Example windowrule v2

-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- windowrulev2 = nomaximizerequest, class:.* # You'll probably like this.

-- check these with hyprland clients

--windowrule = workspace 1, class:org.wezfurlong.wezterm

hl.window_rule({
	name = "match_class_org_qute",
	match = {
		class = "org.qutebrowser.qutebrowser",
	},
	workspace = 8,
})

hl.window_rule({
	name = "match_class_firefox",
	match = {
		class = "firefox",
	},
	workspace = 7,
})

hl.window_rule({
	name = "match_class_vivaldi",
	match = {
		class = "(vivaldi-.*)",
	},
	workspace = 9,
})

hl.window_rule({
	name = "match_class_slack",
	match = {
		class = "slack",
	},
	workspace = 10,
})

--windowrule = float, fullscreen, stayfocused 1, class:hdrop

-- rules for hdrop

--windowrule {

--  name = hdrop_rules

--  match:class = hdrop

--

--  float = on

--  size = 900, 900

--  stay_focused = on

--  center = on

--}

--windowrule = pin, class:hdrop

--windowrule = move 0% 30, class:hdrop

--windowrule = float, pin 1, stayfocused 1, size 700 700, center 1, class:hdrop

--windowrule = float, pin, stayfocused, size 700 700, center 1, move 0 0%, class:hdrop

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

local mainMod = "SUPER"
local altMod = "ALT"
local shiftMod = "SHIFT"
-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("wezterm"))

--bind = $mainMod, T, exec, rio
--bind = $mainMod, T, exec, foot
--bind = $mainMod, Q, exec, kitty
hl.bind(mainMod .. " + " .. "C", hl.dsp.window.close())
hl.bind(mainMod .. " + " .. "M", hl.dsp.exit())
--bind = $mainMod, V, togglefloating
hl.bind(mainMod .. " + " .. "r", hl.dsp.exec_cmd("fuzzel --show drun"))
hl.bind(mainMod .. " + " .. "r", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call launcher toggle"))
hl.bind(mainMod .. " + " .. "l", hl.dsp.exec_cmd("~/.config/hypr/scripts/lockscreen.sh"))
hl.bind(
	mainMod .. " + " .. "v",
	hl.dsp.exec_cmd("cliphist list | fuzzel --dmenu | cliphist decode | wl-copy  && wtype -M ctrl -M shift v")
)
-- hl.bind(
-- 	"Control_L&Shift_L" .. " + " .. "v",
-- 	hl.dsp.exec_cmd("cliphist list| head -n 1| cliphist decode| wl-copy && wtype -M ctrl -M shift v")
-- )
hl.bind(mainMod .. " + " .. "h", hl.dsp.exec_cmd("hdrop -p top -g 20 -- foot --app-id hdrop"))

--# Screenshot a window
--bind = $mainMod, PRINT, exec, hyprshot -m window
--# Screenshot a monitor
--bind = , PRINT, exec, hyprshot -m output
-- Screenshot a region
hl.bind(mainMod .. " + " .. altMod .. " + " .. "p", hl.dsp.exec_cmd("hyprshot -m region"))
-- Move focus with mainMod + arrow keys
--bind = $mainMod, left, movefocus, l
--bind = $mainMod, right, movefocus, r

hl.bind(mainMod .. " + " .. "up", hl.dsp.window.cycle_next())
hl.bind(mainMod .. " + " .. "down", hl.dsp.window.cycle_next({ next = false }))
hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ workspace = "m-1" }))
hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ workspace = "m+1" }))

-- focus switch
for i, v in ipairs({ "left", "right", "up", "down" }) do
	hl.bind(mainMod .. " + " .. altMod .. " + " .. v, hl.dsp.focus({ direction = v }))
end

for i = 1, 10 do
	local key = i % 10 -- 10 maps to key 0
	-- Switch workspaces with mainMod + [0-9]
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	-- Move active window to a workspace with mainMod + SHIFT + [0-9]
	hl.bind(mainMod .. " + " .. shiftMod .. " + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Move active window to another workspace
hl.bind(mainMod .. " + " .. shiftMod .. " + " .. "left", hl.dsp.window.move({ workspace = "e-1" }))
hl.bind(mainMod .. " + " .. shiftMod .. " + " .. "right", hl.dsp.window.move({ workspace = "e+1" }))

-- Move active workspace to monitor
hl.bind(mainMod .. " + " .. altMod .. " + " .. shiftMod .. " + " .. "left", hl.dsp.workspace.move({ monitor = "-1" }))
hl.bind(mainMod .. " + " .. altMod .. " + " .. shiftMod .. " + " .. "right", hl.dsp.workspace.move({ monitor = "+1" }))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + " .. shiftMod .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Hyprshot Screenshots
hl.bind("PRINT", hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind(mainMod .. " + " .. shiftMod .. " + " .. "PRINT", hl.dsp.exec_cmd("hyprshot -m window"))

hl.config({
	ecosystem = {
		no_update_news = true,
	},
})

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("qs -c noctalia-shell --no-duplicate")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("swaync")
	hl.exec_cmd("systemctl --user restart hyprpolkitagent")
	hl.exec_cmd("slack")
	hl.exec_cmd("firefox")
	hl.exec_cmd("qutebrowser")
	hl.exec_cmd("wezterm")
	hl.exec_cmd("kanshi")
end)
