-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

hl.workspace_rule({
    workspace = 1,
    monitor = "desc:Dell Inc. DELL U2721DE 9Y4T023",
})

hl.workspace_rule({
    workspace = 2,
    monitor = "desc:Dell Inc. DELL U2721DE 9Y4T023",
})

hl.workspace_rule({
    workspace = 3,
    monitor = "desc:Dell Inc. DELL U2721DE 9Y4T023",
})

hl.workspace_rule({
    workspace = 4,
    monitor = "desc:Dell Inc. DELL U2721DE 9Y4T023",
})

hl.workspace_rule({
    workspace = 5,
    monitor = "desc:Dell Inc. DELL U2721DE 9Y4T023",
})

hl.workspace_rule({
    workspace = 7,
    monitor = "desc:Dell Inc. DELL U2719DC F8BYX13",
})

hl.workspace_rule({
    workspace = 8,
    monitor = "desc:Dell Inc. DELL U2719DC F8BYX13",
})

hl.workspace_rule({
    workspace = 10,
    monitor = "eDP-1",
})
