-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

hl.workspace_rule({
    workspace = 1,
    monitor = "desc:ViewSonic Corporation VP2458 VKR213640536",
})

hl.workspace_rule({
    workspace = 2,
    monitor = "desc:ViewSonic Corporation VP2458 VKR213640536",
})

hl.workspace_rule({
    workspace = 3,
    monitor = "desc:ViewSonic Corporation VP2458 VKR213640536",
})

hl.workspace_rule({
    workspace = 4,
    monitor = "desc:ViewSonic Corporation VP2458 VKR213640536",
})

hl.workspace_rule({
    workspace = 5,
    monitor = "desc:ViewSonic Corporation VP2458 VKR213640536",
})

hl.workspace_rule({
    workspace = 7,
    monitor = "desc:ViewSonic Corporation VP2458 VKR213640536",
})

hl.workspace_rule({
    workspace = 8,
    monitor = "desc:ViewSonic Corporation VP2458 VKR213640536",
})

hl.workspace_rule({
    workspace = 10,
    monitor = "eDP-1",
})
