-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

for i = 1, 9 do
	hl.workspace_rule({
		workspace = i,
		monitor = "desc:ViewSonic Corporation VP2458 VKR213640536",
	})
end

hl.workspace_rule({
	workspace = 10,
	monitor = "eDP-1",
})
