#:schema https://jj-vcs.github.io/jj/prerelease/config-schema.json
[templates]
#log_node = '''
#label("node",
#  coalesce(
#    if(current_working_copy, label("working_copy", "◉")),
#    if(conflict, label("conflict", "x")),
#    if(immutable, label("immutable", "◆")),
#    if(description.starts_with("TODO: "), label("todo", "!")),
#    label("normal", "○")
#  )
#)
#'''

git_push_bookmark = '''"fra/" ++ change_id.short()'''

log = "log_compact"

# change how describe is presented
draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.summary()),
  ),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\n",
  "JJ: ignore-rest\n",
  diff.git(),
)
'''

