#:schema https://jj-vcs.github.io/jj/prerelease/config-schema.json
[template-aliases]

log_compact = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      format_short_commit_header(self) ++ "\n",
      separate(" ",
        if(empty, label("empty", "(empty)")),
        if(description,
          label(if(description.starts_with("TODO:"), "todo"), description.first_line()),
          label(if(empty, "empty"), description_placeholder),
        ),
      ) ++ "\n",
    ),
  )
)
'''

prompt = '''
separate(" ",
  change_id.shortest(4),
  bookmarks,
  "|",
  concat(
    if(conflict, "💥"),
    if(divergent, "🚧"),
    if(hidden, "👻"),
    if(immutable, "🔒"),
  ),
  raw_escape_sequence("\x1b[1;32m") ++ if(empty, "(empty)"),
  raw_escape_sequence("\x1b[1;32m") ++ if(description.first_line().len() == 0,
    "(no description set)",
    if(description.first_line().substr(0, 29) == description.first_line(),
      description.first_line(),
      description.first_line().substr(0, 29) ++ "…",
    )
  ) ++ raw_escape_sequence("\x1b[0m"),
)
'''

draft_commit_description_alias = '''
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", 
      concat(
        diff.summary(),
        diff.stat(72),
      ),
  )),
  "\n",
  "JJ: ignore-rest\n",
  diff.git(),
)
'''
