# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
#-   repo: local
#    hooks:
#    -   id: format
#        name: format
#        entry: make format
#        language: system
#        types_or: [yaml, python]
