"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[cmd_duration]
min_time = 1

[character]
#error_symbol = "[✗](bold red) "
error_symbol = "[❯](bold red)"
success_symbol = "[❯](green)"

[hostname]
format = "❮$hostname❯ "
disabled = false

[username]
style_user = "bold dimmed blue"
show_always = true

[directory]
truncation_length = 10
truncate_to_repo = false

[time]
disabled = false
time_format = "%T"

[battery]
disabled = false
#full_symbol = "🔋"
charging_symbol = "⚡️"
#discharging_symbol = "💀"

[[battery.display]]
threshold = 30
style = "bold red"

[jobs]

[memory_usage]
threshold = 80
style = "bold dimmed green"
disabled = false
format = "$symbol [${ram}( | ${swap})]($style) "

[git_branch]
style = "bold yellow"
only_attached = true
disabled = true

[git_status]
conflicted = "⚔️ "
#diverged = "🔱 "
#untracked = "🛤️ "
#untracked = "[$count](green)🤷"
#stashed = "[$count](bold red)📦 "
#modified = "[$count](red)📝 "
#staged = "[$count](blue)🗃️ "
#renamed = "📛 "
#deleted = "🗑"
style = "black"
ahead = "⇡${count}"
behind = "⇣${count}"
disabled = true

[git_commit]
#commit_hash_length = 7
only_detached = false
format = "[\\($hash\\)]($style) "
disabled = true

[git_state]
format = "[\\($state( $progress_current of $progress_total)\\)]($style) "
disabled = true
#cherry_pick = "[🍒 PICKING](bold red)"

[python]

[perl]
format = "[$symbol($version )]($style)"

[status]
disabled = false
format = " [$symbol$status]($style) "

[kubernetes]
disabled = false
detect_env_vars = ['K8S']
#detect_files = ['k8s'] # for some reason this needs to be 

# [custom.jj]
# when = "jj-starship detect"
# shell = ["jj-starship", "--strip-bookmark-prefix", "fra/"]
# format = "$output "

[custom.jj]
ignore_timeout = true
description = "current jj status"
detect_folders = [".jj"]
symbol = "🥋 "
when = true
command = 'jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template prompt'

#command = '''
#jj log -r@ -l1 --ignore-working-copy --no-graph --color always  -T '
#  separate(" ",
#    branches.map(|x| x.name()).join(" "),
#    if(conflict, "conflict"),
#    if(divergent, "divergent"),
#    if(hidden, "hidden"),
#  )
#'
#'''
#symbol = "jj"

#[custom.jjstate]
#detect_folders = [".jj"]
#command = '''
#jj log -r@ -n1 --no-graph -T "" --stat | tail -n1 | perl -pE 's/(\d+) files? changed, (\d+) insertions?\(\+\), (\d+) deletions?\(-\)/$1m $2+ $3-/'
#'''
